### ISSUE TITLE
Better defaults for readability for interactive usage?

### ISSUE THREAD

**Issue by jrivers96** [Paradigm4/SciDB-Py#111]
@apoliakov @ksens 
I find myself always turning on as_dataframe for fetch statements in a Python notebook. It makes things a lot more readable.  Is there any reason that we wouldn't want to include this by default?
``
db.summarize(KG_VARIANT).fetch(as_dataframe=True)
``
![image](https://user-images.githubusercontent.com/11034356/31623569-d13ccd84-b26d-11e7-98ce-4337f23cc6fd.png)

**Comment by ksens** [comment]
Yes, seems it would be useful to turn on by default.

Potentially, have a global flag that allows you to choose the default download method. 

In R, one could do something like

```R
options(scidb.default_download_as_data_frame = TRUE)
```

and everything reads off this option flag if not specifically set by user.

**Comment by rvernica** [comment]
In Python Notebooks I also had to do a lot of `fetch(as_dataframe=True)` instead of the simple `[:]`.

The reason that is not the default is the support for nulls. Pandas DataFrames do not fully support nulls. More exactly, an `int64` null-able attribute in SciDB, would become a `double` in Pandas so that any null values can be represented as `NaN`. See [here](https://pandas.pydata.org/pandas-docs/stable/gotchas.html#nan-integer-na-values-and-na-type-promotions) for more details on Pandas null support and type promotions.

In SciDB-Py, the default is NumPy which very accurately represents the SciDB types. So, you can download an array and upload it back without changing its data:
```python
foo = db.scan('foo').fetch(atts_only=True)
db.load('foo', upload_data=foo)
# foo is unchanged
```

**Comment by rvernica** [comment]
Instead of changing the defaults for `fetch` we can change what `[:]` does. It currently returns NumPy, so we can have it return Pandas. In this case, the `fetch` defaults remain unchanged. So, one can do:
```python
db.arrays.foo[:] 
db.scan('foo')[:]
```
and get Pandas back (instead of NumPy).

**Comment by ksens** [comment]
👍 

Keeping `fetch` unchanged, and changing `[:]` sounds good to me.

**Comment by rvernica** [comment]
@apoliakov @jrivers96 are you OK with changing `[:]` to return Pandas instead of NumPy? `fetch` will remain unchanged.

**Comment by apoliakov** [comment]
Yes. Sounds good

**Comment by ksens** [comment]
👍

**Comment by apoliakov** [comment]
Hey Rares, did you get a chance to make this change?

**Comment by rvernica** [comment]
Not yet, I will look into it.
