### ISSUE TITLE
Helper function requested - head

### ISSUE THREAD

**Issue by jrivers96** [Paradigm4/SciDB-Py#113]
When using Pandas, you can use head() to quickly see what data you are working with. It would be nice to be able to do this with the SciDB-Py package and return.

https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.head.html

``
#user types
head(KG_VARIANT,5)

#e.g.
method head(array_name, n):
db.limit(array_name, n).fetch(as_dataframe=True)
``

**Comment by rvernica** [comment]
In R the `head` syntax is:
```R
head(df, 5)
```
In Pandas, the syntax is:
```python
df.head(5)
```
So, would something like:
```python
db.arrays.foo.head(5)
```
work in SciDB-Py? Also, we can have `head` return a Pandas DataFrame since `head` is more of a DataFrame method.

This requires that the `limit` plugin is available in SciDB. So, SciDB-Py would check if the `limit` operator is available first. If not, `db.arrays.foo.head(5)` results in `db.arrays.foo.fetch(as_dataframe=True)[:5]` which fetches the entire array and then slices it.


BTW, another way to fetch data from an array is `db.arrays.foo[:]`, so we could have `db.arrays.foo[:5]` use `limit` instead of fetching the entire array and then slicing it. Lower bounds or negative values won't trigger the use of `limit` and the entire array will be fetched and sliced afterwards. This opens the question of multi-dimensional slicing for multi-dimensional arrays. So, something like `db.arrays.foo[1:2][3:4]` could use `between(foo, 1, 3, 2, 4)`.

**Comment by ksens** [comment]
My 2c.

My understanding is that you currently do:

```py
db.arrays.foo.OPERATOR(....)
```

where OPERATOR is any of the loaded operators on the system. 

Since `limit` is going to be default from 17.9 onwards, I would suggest just using

```py
db.arrays.foo.limit(5)[:]
```

Overloaded functions should be minimized wherever possible. We went down the road of using overloaded functions like `head`, `merge`, `subset` in R, and then totally gave up on it. Eventually, we gave up trying to hide AFL in the `scidbR` package. 

Also, while training folks with overloaded `head`, I have seen people expecting `head` to be a scidb operator, and then trying it in AFL. 

A `dplyr` / `scidb4gh` kind of layer on top of `scidbr` might make overloaded operators, but the core `scidb-r`, `scidb-py` engines should probably not do that. 

@rvernica Unless of course, you are using a lot of overloaded operators already in the scidb-py package.

**Comment by jrivers96** [comment]
@ksens 
Anything that we can do for the user to create a more efficient experience is preferable. A customer of ours was a big fan of the R tibble because of it's usability features. Some of the features I am after here is nice printouts and syntax that a Pandas user would typically use. 

https://cran.r-project.org/web/packages/tibble/vignettes/tibble.html

I agree that implementing merge and subset were a problem as this is a complex optimization problem, but head is a one to one simple mapping. 

@rvernica 

I like the idea of having head return a Pandas DataFrame. This gives me the readable printout and head function that I'm used to when working with Pandas.  This is up to you if you'd like to incorporate this.

**Comment by ksens** [comment]
@jrivers96 I see your point about `head` allowing a better UX. 

Yes, `tibble` is super useful.

**Comment by rvernica** [comment]
Since b14fe1c1f4afbd78507c7e7d81d2b4fe94bca804 one can do:
```python
In [3]: db.iquery('store(build(<x:int64>[i=0:100], i), foo)')

In [4]: db.arrays.foo[:].head()
/home/rares/.local/lib/python3.6/site-packages/scidbpy/schema.py:632: UserWarning: 1 type(s) promoted for null support. Precision loss may occur
  dtype=self.get_promo_atts_dtype())
Out[4]: 
   i    x
0  0  0.0
1  1  1.0
2  2  2.0
3  3  3.0
4  4  4.0
```
This *does not* use `limit` and fetches the entire array in Python.

**Comment by rvernica** [comment]
You can now do:
```python
In [19]: db.arrays.foo.head()
.../scidbpy/schema.py:632: UserWarning: 1 type(s) promoted for null support. Precision loss may occur
  dtype=self.get_promo_atts_dtype())
Out[19]: 
   i    x
0  0  0.0
1  1  1.0
2  2  2.0
3  3  3.0
4  4  4.0
```
and this results in `limit(foo, 5)` being executed. Variants are available as well:
```python
In [27]: db.arrays.foo.head(10)
.../scidbpy/schema.py:632: UserWarning: 1 type(s) promoted for null support. Precision loss may occur
  dtype=self.get_promo_atts_dtype())
Out[27]: 
   i    x
0  0  0.0
1  1  1.0
2  2  2.0
3  3  3.0
4  4  4.0
5  5  5.0
6  6  6.0
7  7  7.0
8  8  8.0
9  9  9.0

In [28]: db.arrays.foo.head(10, atts_only=True)
.../scidbpy/schema.py:632: UserWarning: 1 type(s) promoted for null support. Precision loss may occur
  dtype=self.get_promo_atts_dtype())
Out[28]: 
     x
0  0.0
1  1.0
2  2.0
3  3.0
4  4.0
5  5.0
6  6.0
7  7.0
8  8.0
9  9.0

In [29]: db.arrays.foo.head(10, atts_only=True, as_dataframe=False)
Out[29]: 
array([((255, 0),), ((255, 1),), ((255, 2),), ((255, 3),), ((255, 4),),
       ((255, 5),), ((255, 6),), ((255, 7),), ((255, 8),), ((255, 9),)],
      dtype=[('x', [('null', 'u1'), ('val', '<i8')])])
```
If `limit` is not available, the following happens:
* A warning is issued
* The entire array is fetched
* The output is sliced and returned
```python
In [17]: db.arrays.foo.head()
.../scidbpy/db.py:529: UserWarning: "limit" operator not available. Fetching the entire array. See https://github.com/Paradigm4/limit.
  'See https://github.com/Paradigm4/limit.')
.../scidbpy/schema.py:632: UserWarning: 1 type(s) promoted for null support. Precision loss may occur
  dtype=self.get_promo_atts_dtype())
Out[17]: 
   i    x
0  0  0.0
1  1  1.0
2  2  2.0
3  3  3.0
4  4  4.0
```
`head` is *not* available for operators, so this does not work:
```python
In [21]: db.scan('foo').head()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-21-a948f5aa9128> in <module>()
----> 1 db.scan('foo').head()

~/proj/scidb-py/scidbpy/db.py in __getattr__(self, name)
    697             raise AttributeError(
    698                 '{.__name__!r} object has no attribute {!r}'.format(
--> 699                     type(self), name))
    700 
    701     def __dir__(self):

AttributeError: 'Operator' object has no attribute 'head'
```
Instead, one can do:
```
In [23]: db.scan('foo').limit(5)[:]
.../scidbpy/schema.py:632: UserWarning: 1 type(s) promoted for null support. Precision loss may occur
  dtype=self.get_promo_atts_dtype())
Out[23]: 
   i    x
0  0  0.0
1  1  1.0
2  2  2.0
3  3  3.0
4  4  4.0
```

**Comment by jrivers96** [comment]
Great!  We will test this out. Thanks!
