### ISSUE TITLE
Dependence on afldb.py creating issues in SciDB15.7

### ISSUE THREAD

**Issue by ksens** [Paradigm4/SciDB-Py#84]
There seems to be a problem with the current design of importing AFL operators when working with SciDB 15.7. I have tested a solution on my local version, and will describe this here. If there are no objections to my proposed solution, I will push my local changes to the GitHub repo.

Current design 
===========

 - Currently AFL operators are imported into SciDB-py using ``afldb.py``, which in turn is generated using scripts at the `scidb-aflgen` repo (https://github.com/Paradigm4/scidbpy-aflgen). 
 - The advantage of using this method is that ``scidb-aflgen`` scrapes through the SciDB source code and Doxygen generated man files and generates a list of operators and their help info (a.k.a. DocStrings). 
 - This auto-generated list of operators and DocStrings is stored in `afldb.py` and copied over to the `scidbpy` folder in SciDB-py
 - Now, `afl.py` in SciDB-py looks for operators defined in `afldb.py` and loads those (plus some manually added operators like `gemm(), gesvd()`) into the SciDB-py AFL namespace

Problem
======

 - When the above procedure was carried out for SciDB-py 15.7, an updated list of AFL operators was created. 
 - However in SciDB-15.7, `load()` is no longer considered an operator; it is a macro instead. 
 - So the SciDB-py unit tests that were using `load()` started failing when using the updated list of operators. 

Proposed solution
==============

Instead of importing the AFL operators through `afldb.py`, here is what I propose:

 - The actual list of supported AFL operators and macros would be found by running the following queries from Python:
```Python
iquery -aq "list('operators')"
iquery -aq "list('macros')"
```

 - The iquery output would then be parsed to get the list of operators and macros that are supported in the version of SciDB that is installed on that machine. 
 - This means SciDB-py should now work across different versions of SciDB (i.e. support a different list of operators). 
 - Also, operators available through custom plugins should also be available to SciDB-py in this fashion. 

But what about the documentation?
-----------------------------------------------

So far in my proposed solution, `afldb.py` has not been used and so the DocStrings have not been made available to SciDB-py. To solve this, the next part of the solution is as follows:
 - for every operator/macro imported through the above process, SciDB-py would look for a corresponding DocString in `afldb.py`. 
 - If found, that DocString would be imported over. If not, the operator would still be available (but just without any documentation).

How does this sound? If there are no objections, I will push these changes into GitHub from my local version.

**Comment by ChrisBeaumont** [comment]
I have some thoughts:

* Querying SciDB to get the exact operator list available is a great idea. You could use the result of that query to populate the namespace of scidbpy.afl automatically (and as you mention you could even get fancy and update that namespace on the fly, when a users loads an additional SciDB plugin).

* The fact that scidbpy-aflgen doesn't find `load()` anymore is an implementation detail that could be fixed, if you wanted

* It's not true that afldb.py has been unused -- it is imported and used in `afl.py`, and the docstrings in `afldb.py` determine what you see when you type `help(scidbpy.afl.project)` or `scidbpy.afl.project?` in IPython. Note that these docstrings are formatted differently than those in afldb.rst, which generate the *html* documentation. 

In general I like the approach of using a dynamic query to discover additional operators that are not in afldb.py, and add functions for them (without docstrings). But I think the docstring parsing that happens when building `afldb.py` and `afldb.rst` is valuable, so it's worth trying to fix the parsing of macros. 

The *really* cool approach (which I don't think is possible) is to query SciDB to return the documentation for its own operators, and use that to build docstrings instead of building `afldb` files offline. However if I remember correctly the documentation for functions inside SciDB is either absent or much more terse than the documentation that ends up in doxygen.

**Comment by jmcq** [comment]
Understand that I have never even looked at afldb.py  -- perhaps what I am
about to suggest is how it works.

Doxygen generates HTML web pages that can be served.  Perhaps a python
program could use a curl library to scrape the served Doxygen for the
documentation you are looking for.

Again, forgive me if this is part of one of the workflows already ... I am
trying to throw out ideas that might stimulate others -- I am not trying to
suggest that this is the right solution.

**Comment by ksens** [comment]
@ChrisBeaumont : You wrote:
> "It's not true that `afldb.py` has been unused -- it is imported and used in `afl.py`, and the docstrings in afldb.py determine..."

I absolutely agree with you. Hence I never wanted to suggest that `afldb.py` was not being used. In fact, I realize now that my writeup of the solution might have been confusing. I just edited that in the last section: **"But what about the documentation?"**

The functionality of getting the DocStrings through `afldb.py` is very useful, and will be retained in my solution. Just that the result of the `iquery` output will be taken as the gold truth.

**Comment by ksens** [comment]
@jmcq : Here's how the scidb-aflgen script https://github.com/ChrisBeaumont/scidbpy-aflgen works:

- It loops through all the files in SciDB source directory matching the wildcard `Logical*cpp`
- Then it searches for `DECLARE_LOGICAL_OPERATOR_FACTORY` within each such file. 
- Then it does regex matching on such lines (example below) to find the name of the operator in each file:
```
DECLARE_LOGICAL_OPERATOR_FACTORY(LogicalCreateArray,     "create_array")
```
- At this point it has operator name (`create_array` in the above example) and can also formulate the path to the Doxygen raw output (which is in a JSON format)
- It reads the JSON formatted inputs directly into Python (which is a predecessor to the HTML documentation) and generates DocStrings from there

There might be some benefits to using Curl over the above method -- I will need to look into this. @ChrisBeaumont : Any inputs to that?

**Comment by ChrisBeaumont** [comment]
Parsing the Doxygen-generated HTML instead of the current approach of parsing the manfiles and source code may be cleaner. I may have even tried this originally, though I can't remember (I suspect that I decided that the man files were easier to parse than the HTML files).  

Anyways, I'm on board with the general approach of combining some kind of offline parsing of static files with an online SciDB query, to gather as much information as possible. 

One other thing to keep in mind: we should make sure that readthedocs.org can always generate reasonable documentation without access to a running SciDB instance.

**Comment by jmcq** [comment]
BTW, I was suggesting to scrape the Doxygen vs the manuals because in
Bryan's opinion (and I think he's right) the Doxygen doc is more useful /
complete / informative than our manuals are. [ Here I am guessing that by
"manpages" Chrs Beaumont means SciDB .PDF and HTML reference manual -- if
not please correct me.]

Because the manual is written by a non-programmer, it sometimes lacks
details that programmers from another programming language would be
interested in.   In many ways the Doxgen is a "primary source" and the
manual a "secondary source" in the sense of the latter being a derivative
product.

Hope I'm only adding useful info -- if I am not helping please feel free to
ignore my commentary.

**Comment by jrivers96** [comment]
The manuals are the man files created from doxygen. They are the files utilized by the Linux man command.

**Comment by jmcq** [comment]
Ah, I see, I only look at doxygen output via webpages, I did not even
realize it could generate the "man" form.  Thanks for clearing this up for
me.

**Comment by ksens** [comment]
Thanks for inputs. 

Closing this issue by pushing proposed changes in commit https://github.com/Paradigm4/SciDB-Py/commit/c6d715e2a5ef439cf8164889c39d6a8be47c0e80

**Comment by ChrisBeaumont** [comment]
Hi @ksens 

This is obviously up to you, but you might consider proposing changes like this in pull requests instead of pushing commits directly to the master branch. For instance, while I'm on board with the *conceptual* plan outlined in this issue, I have some minor questions / reservations about some implementation details in c6d715e.

**Comment by ksens** [comment]
@ChrisBeaumont:

I agree with your comment. Will definitely suggest future changes through pull requests.
